export const mockFarmers = [
  {
    id: "1",
    name: "राम कुमार शर्मा",
    location: "Sonipat, Haryana",
    crops: ["Wheat", "Rice", "Sugarcane"],
    farmSize: "15",
    experience: "12",
    organicCertified: true,
    rating: 4.8,
    phone: "+91 98765 43210",
    email: "ram.sharma@example.com",
    description: "Experienced farmer specializing in organic wheat and rice production.",
    verified: true,
  },
  {
    id: "2",
    name: "सुनीता देवी",
    location: "Ludhiana, Punjab",
    crops: ["Cotton", "Maize", "Vegetables"],
    farmSize: "8",
    experience: "8",
    organicCertified: false,
    rating: 4.5,
    phone: "+91 98765 43211",
    email: "sunita.devi@example.com",
    description: "Cotton and vegetable farmer with modern farming techniques.",
    verified: true,
  },
  {
    id: "3",
    name: "अजय पटेल",
    location: "Ahmedabad, Gujarat",
    crops: ["Cotton", "Groundnut", "Cumin"],
    farmSize: "20",
    experience: "15",
    organicCertified: true,
    rating: 4.9,
    phone: "+91 98765 43212",
    email: "ajay.patel@example.com",
    description: "Large scale cotton and spice farmer with organic certification.",
    verified: true,
  },
  {
    id: "4",
    name: "मुकेश यादव",
    location: "Nashik, Maharashtra",
    crops: ["Grapes", "Onions", "Sugarcane"],
    farmSize: "12",
    experience: "10",
    organicCertified: false,
    rating: 4.3,
    phone: "+91 98765 43213",
    email: "mukesh.yadav@example.com",
    description: "Grape and onion farmer with focus on quality produce.",
    verified: true,
  },
  {
    id: "5",
    name: "रवि कुमार",
    location: "Coimbatore, Tamil Nadu",
    crops: ["Rice", "Coconut", "Turmeric"],
    farmSize: "6",
    experience: "7",
    organicCertified: true,
    rating: 4.6,
    phone: "+91 98765 43214",
    email: "ravi.kumar@example.com",
    description: "Organic rice and spice farmer with traditional methods.",
    verified: true,
  },
  {
    id: "6",
    name: "गीता शर्मा",
    location: "Jaipur, Rajasthan",
    crops: ["Bajra", "Mustard", "Gram"],
    farmSize: "10",
    experience: "9",
    organicCertified: false,
    rating: 4.4,
    phone: "+91 98765 43215",
    email: "geeta.sharma@example.com",
    description: "Desert crop specialist with water-efficient farming.",
    verified: true,
  },
  {
    id: "7",
    name: "संजय सिंह",
    location: "Kanpur, Uttar Pradesh",
    crops: ["Wheat", "Potato", "Peas"],
    farmSize: "18",
    experience: "14",
    organicCertified: false,
    rating: 4.7,
    phone: "+91 98765 43216",
    email: "sanjay.singh@example.com",
    description: "Wheat and vegetable farmer with high yield varieties.",
    verified: true,
  },
  {
    id: "8",
    name: "प्रिया राव",
    location: "Bangalore, Karnataka",
    crops: ["Coffee", "Cardamom", "Pepper"],
    farmSize: "5",
    experience: "6",
    organicCertified: true,
    rating: 4.8,
    phone: "+91 98765 43217",
    email: "priya.rao@example.com",
    description: "Organic coffee and spice plantation owner.",
    verified: true,
  },
]

export const mockDistributors = [
  {
    id: "d1",
    businessName: "Agro Products Ltd",
    ownerName: "राज सिंह",
    businessType: "Wholesale Distributor",
    state: "Punjab",
    district: "Ludhiana",
    cropsInterested: ["Wheat", "Rice", "Cotton"],
    minOrderQuantity: "50",
    experience: "15",
    rating: 4.7,
    phone: "+91 98765 54321",
    email: "raj@agroproducts.com",
    description: "Leading wholesale distributor for grains and cotton in North India.",
    certifications: ["FSSAI License", "Import/Export License"],
    verified: true,
  },
  {
    id: "d2",
    businessName: "Fresh Farm Distributors",
    ownerName: "अनिता गुप्ता",
    businessType: "Retail Chain",
    state: "Maharashtra",
    district: "Pune",
    cropsInterested: ["Vegetables", "Fruits", "Organic Produce"],
    minOrderQuantity: "20",
    experience: "8",
    rating: 4.5,
    phone: "+91 98765 54322",
    email: "anita@freshfarm.com",
    description: "Retail chain specializing in fresh vegetables and organic produce.",
    certifications: ["FSSAI License", "Organic Certification"],
    verified: true,
  },
  {
    id: "d3",
    businessName: "Export Excellence",
    ownerName: "विकास शर्मा",
    businessType: "Export Company",
    state: "Gujarat",
    district: "Ahmedabad",
    cropsInterested: ["Cotton", "Groundnut", "Cumin", "Spices"],
    minOrderQuantity: "100",
    experience: "12",
    rating: 4.9,
    phone: "+91 98765 54323",
    email: "vikas@exportexcellence.com",
    description: "Premium export company for cotton, spices and oil seeds.",
    certifications: ["Import/Export License", "ISO Certification"],
    verified: true,
  },
  {
    id: "d4",
    businessName: "Grain Masters Co-op",
    ownerName: "सुरेश पटेल",
    businessType: "Cooperative Society",
    state: "Madhya Pradesh",
    district: "Indore",
    cropsInterested: ["Wheat", "Soybean", "Maize"],
    minOrderQuantity: "30",
    experience: "20",
    rating: 4.6,
    phone: "+91 98765 54324",
    email: "suresh@grainmasters.com",
    description: "Farmer cooperative specializing in grain procurement and distribution.",
    certifications: ["FSSAI License", "Cooperative Registration"],
    verified: true,
  },
  {
    id: "d5",
    businessName: "South Spice Trading",
    ownerName: "लक्ष्मी नायर",
    businessType: "Processing Unit",
    state: "Kerala",
    district: "Kochi",
    cropsInterested: ["Pepper", "Cardamom", "Coffee", "Coconut"],
    minOrderQuantity: "15",
    experience: "10",
    rating: 4.8,
    phone: "+91 98765 54325",
    email: "lakshmi@southspice.com",
    description: "Spice processing and trading company with international reach.",
    certifications: ["FSSAI License", "HACCP Certification"],
    verified: true,
  },
  {
    id: "d6",
    businessName: "Desert Crop Traders",
    ownerName: "मोहन लाल",
    businessType: "Individual Trader",
    state: "Rajasthan",
    district: "Jodhpur",
    cropsInterested: ["Bajra", "Mustard", "Gram", "Guar"],
    minOrderQuantity: "25",
    experience: "18",
    rating: 4.4,
    phone: "+91 98765 54326",
    email: "mohan@desertcrop.com",
    description: "Specialized trader for desert crops and drought-resistant varieties.",
    certifications: ["FSSAI License"],
    verified: true,
  },
]
